Fix Resource.url property access
Changed from fmt.root_resource.get_url() to fmt.root_resource.url
since Resource has a 'url' property, not a 'get_url()' method.

Fixes AttributeError: 'Resource' object has no attribute 'get_url'